//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp6
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrder
    {
        public int Id { get; set; }
        public int GameId { get; set; }
        public string PartName { get; set; }
        public int Quantity { get; set; }
        public int DeliveryCounter { get; set; }
        public System.DateTime OrderDate { get; set; }
    
        public virtual GameSession GameSession { get; set; }
    }
}
